service: simple-data-pipline # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}

#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#      - "dynamodb:*"
#      Resource:
#      - "Fn::GetAtt": [DocumentsTable, Arn]
#      - "Fn::Join":
#        - "/"
#        - - { "Fn::GetAtt": [DocumentsTable, Arn] }
#          - "index/*"
#    - Effect: "Allow"
#      Action:
#        - "s3:GetObject"
#      Resource:
#        Fn::Join: ['', [Fn::GetAtt: [ S3BucketDocuments, Arn ], '/*'] ]

#custom:
#  tableThroughputs:
#    production: 5
#    default: 1
#    tableThroughput: ${self:custom.tableThroughputs, self:custom.tableThroughputs.default}
#  documentsTableName: $DocumentsTable

#plugins:
#   - serverless-pseudo-parameters

functions:
  hello:
    handler: handler.importCSVToDB
#    environment:
#      documentsTable: ${self:custom.documentsTableName}
#    events:
#      - s3:
#          bucket:  { Ref: DocumentsTable }
#          event: s3:ObjectCreated:*
#          rules:
#            - suffix: .csv

#resources:
#  # DynamoDB
#  - ${file(resources/dynamodb-table.yml)}
#  # S3
#  - ${file(resources/s3-bucket.yml)}